// Test code
start = millis()

function sum (a, b)
	return a + b
end

println("loop 3 times")
for (jj = 0; jj < 3; jj++)
	println("jj == " + jj)
end

ii = 0
println("loop 5 times")
while (ii < 5)
	print("ii == " + ii + " - ")
	if ((ii & 1) == 1)
	    print("odd ")
	elif (ii == 2)
	    print(" bingo! ")
	else
	    print("even ")
	ii = sum(ii, 1)
	println("")
end
println("done")
time = millis() - start
return "execution time " + time + " ms"